org: pelshen
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: name-draw
service: name-draw

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs22.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/name-draw*"

functions:
  slack:
    handler: app.handler
    events:
      - http:
          method: post
          path: slack/events
      - http:
          method: get
          path: slack/installation
      - http:
          method: get
          path: slack/oauth

resources:
  Resources:
    installationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: name-draw_installation
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  serverless-dynamodb:
    start:
      migrate: true
      seed: true

    seed:
      domain:
        sources:
          - table: name-draw_installation
            sources: [./installation-seed.json]
