name: Build all

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm ci, build, and test
        run: |
          npm ci --workspaces
          npm run build --workspaces --if-present
          npm run test --workspaces --if-present
      
      - name: npm ci and test slack app
        run: |
          cd slack app
          npm ci
          npm run test