name: Build Node.js slack app

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './slack app'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: npm ci, build, and test
        run: |
          npm ci
          npm run build --workspaces --if-present
          npm run test --workspaces --if-present
